CREATE DATABASE IF NOT EXISTS xboxsurvey
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci;

USE xboxsurvey;

CREATE TABLE IF NOT EXISTS reponses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100) NOT NULL,
    age VARCHAR(20) NOT NULL,
    sexe VARCHAR(30) NOT NULL,
    temps VARCHAR(30) NOT NULL,
    avis TEXT,
    note INT CHECK (note BETWEEN 1 AND 5),
    fav VARCHAR(100) NOT NULL,
    date_reponse DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
